config/routes.rb
Tickets::Application.routes.draw do
  resources :notes

  resources :items

  resources :users

  resources :locations

  resources :contacts

  resources :tickets

  resources :rooms

  root :to => "tickets#index"

  match "login" => "user_auth#login"
  match "welcome" => "user_auth#welcome"
  match "logout" => "user_auth#logout"  
  match "lookup" => "tickets#lookup"
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  
  belongs_to :location
  belongs_to :room
  belongs_to :user
  belongs_to :contact
  has_many :notes
  belongs_to :item
 
  validates :room, :presence => true
  validates :subject, :presence => true
  

  def self.possible_statuses?
    ["Open", "Closed", "Pending"]
  end

  def self.possible_types?
    ["Repair", "Integration", "Service"]
  end

  def location
    if self.room then room.location else location end
  end
  
  def opened_at?
    if self.opened_at then self.opened_at else self.created_at end
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  layout 'main'

  before_filter :login_required
  before_filter :require_https




  # GET /tickets
  # GET /tickets.xml

  def index
      @content_for_title = "Tickets: Index"


    if params[:filter].nil? then
      params[:filter] = Hash.new
      params[:filter][:status] = "Open"
      params[:filter][:ticket_type] = "Repair"
    end

    if params[:filter][:status] == "All" && params[:filter][:ticket_type] == "All" then
      @tickets = Ticket.find(:all, :order => "opened_at DESC")
      @filter = params[:filter]
    elsif params[:filter][:status] == "All" then
      @tickets = Ticket.where(:ticket_type => params[:filter][:ticket_type]).order(:opened_at).reverse_order 
      @filter = params[:filter]
    elsif params[:filter][:ticket_type] == "All" then
      @tickets = Ticket.where(:status => params[:filter][:status]).order(:opened_at).reverse_order
      @filter = params[:filter]
    else
      @tickets = Ticket.where(params[:filter]).order(:opened_at).reverse_order
      @filter = params[:filter]
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tickets }
      format.js
    end
  end

  def lookup
    @location = Location.find(params[:ticket][:location_id])
    @rooms = @location.rooms
    respond_to do |format|
      format.js
    end
  end


  def get_rooms
    render :layout => false
    render :text => 'raaagh'
  end

  # GET /tickets/1
  # GET /tickets/1.xml
  def show
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.xml
  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.xml
  def create
    
    tik = Ticket.new(params[:ticket])
    tik.user = current_user
    @ticket = tik
    if !@ticket.opened_at then @ticket.opened_at = Time.now end

    respond_to do |format|
     if @ticket.save
         format.html { redirect_to(@ticket, :notice => 'Ticket was successfully created.') }
         format.xml  { render :xml => @ticket, :status => :created, :location => @ticket }
       else
         format.html { render :action => "new" }
         format.xml  { render :xml => @ticket.errors, :status => :unprocessable_entity }
     end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.xml
  def update
    @ticket = Ticket.find(params[:id])
    if @ticket.status != "Closed" && params[:ticket]["status"] == "Closed" && 
      params[:ticket]["closed_at"].blank? then
      params[:ticket]["closed_at"] = Time.now.to_s
    end

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to(@ticket, :notice => 'Ticket was successfully updated. ' + params[:ticket]["closed_at"]) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ticket.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.xml
  def destroy
    if current_user.can_write_tickets? then
      @ticket = Ticket.find(params[:id])
      @ticket.destroy
    end

    respond_to do |format|
      format.html { redirect_to(tickets_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
  <% if @ticket.errors.any? %>
    <div id="error_explanation" class="append-5 last">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div><br />
  <% end %>

<div class="span-12">
<div class="span-5 ">
<%= label_tag "Site" %>
   <div class="span-5 "> 
<%= form_tag lookup_path, :method => :get, :remote => true, :id => 'location' do %>
  <%= collection_select(:ticket, :location_id, Location.find(:all, :order => "NAME"), :id, :name, {:prompt => true}, {:onchange => "$('location').request();"}) %>
  </div>
</div>
<% end %>


<%= form_for(@ticket) do |f| %>

    <div class="span-4">
    <%= f.label :room %>
   <div id="rooms" class="span-4 field">
   <%= if @ticket.room then collection_select(:ticket, :room_id, @ticket.location.rooms, :id, :name) else 
    select_tag("ticket[room_id]", "<option>Please select Site first</option>".html_safe)
   
   end %>
  
   </div>
   </div>

   <div id="location_hidden">
    <%= f.hidden_field(:location_id) %>
   </div>
   <div id="hidden_fields">
    
   </div>

   <div class="span-4 append-2 field last">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="span-12 field last">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
    <div class="span-3 field">
     <%= f.label :status %><br />
     <%= select(:ticket, :status, Ticket.possible_statuses?) %>
   </div>

   <div class="span-3 field ">
     <%= f.label :type %><br />
     <%= select(:ticket, :ticket_type, Ticket.possible_types?) %>
   </div>

  <div class="span-4 field last">
     <%= f.label :client_ticket %><br />
    <%= f.text_field :client_ticket_number %>
   </div>


   <div class="span-6 field">
    <%= f.label :contact_name %>
    <%= f.text_field :quick_contact_name %>
   </div>

   <div class="span-6 field last">
    <%= f.label :contact_telephone %>
    <%= f.text_field :quick_contact_telephone %>
   </div>

   <div class="span-6 field">
     <%= f.label :opened_at %><br />
     <%= f.calendar_date_select "opened_at" %>
   </div>
   <div class="span-6 field last">
     <%= f.label :closed_at %><br />
     <%= f.calendar_date_select "closed_at" %>
   </div>


  <div class="span-1 actions last">
    <%= f.submit %>
  </div>

<% end %>
</div>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<div class="span-4 append-20 last"
<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>
</div>

app/views/tickets/index.html.erb
<div class="span-1 smallbox">
Status:
</div>
<div class="span-6 append-8 last">
<%= form_tag tickets_path, :method => :get, :id => 'filter' do %>
  <%= select_tag "filter[status]", options_for_select(Ticket.possible_statuses? << "All", @filter[:status]), {:prompt => true, :onchange => "$('filter').submit();"} %> 
  &nbsp Type:
  <%= select_tag "filter[ticket_type]", options_for_select(Ticket.possible_types? << "All", @filter[:ticket_type]), {:prompt => true, :onchange => "$('filter').submit();"} %> 
<% end %>

</div>


<table>
  <tr>
    <th>Case Number</th>
    <th>Site</th>
    <th>Room</th>
    <th>Type</th>
    <th>Subject</th>
    <th>Opened at</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tickets.each do |ticket| %>
  <tr>

    <td><%=h  "%06d" % ticket.id %></td>
    <td><%= ticket.location.name %></td>
    <td><%= ticket.room.name %></td>
    <td><%= ticket.ticket_type %></td>
    <td><%= ticket.subject %></td>
    <td><%= ticket.opened_at%></td>
    <td><%= ticket.status %></td>
    <td><%= link_to 'Show', ticket %></td>

    <% if current_user.can_write_tickets? && ticket.user == current_user then %>
    <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
    <td><%= link_to 'Destroy', ticket, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>


<% if @tickets.blank? then %>
<%= "<b>No tickets match the filter criteria.</b><br />".html_safe %>
<% end %>
<br />


<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/lookup.js.erb
var data =  <%=h sanitize(@rooms.order(:name).to_json(:only => [:name, :id]))%>;

var location_id = <%=h @location.id %>;

var hidden = document.getElementsByTagName('hidden')[1];

var select = document.getElementsByTagName('select')[1];
select.options.length = 0; // clear out existing items
for(var i=0; i < data.length; i++) {
    var d = data[i];
    select.options.add(new Option(d.name, d.id))
}

$('hidden_fields').update('<input type="hidden" value="<%=h @location.id %>" name="ticket[location_id]" id="ticket_location_id">')

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

<div class="span-4 append-20 last">
<%= link_to 'Back', tickets_path %>
</div>

app/views/tickets/show.html.erb
<div class="span-16 append-6 last">
<span id="notice"><%= notice %></span>
</div>


<%=h item("Case number:", "%06d" % @ticket.id) %>

<%=h item("Opened:", @ticket.opened_at.to_s) %>

<%=h item("Created by:", @ticket.user.first_name + " " + @ticket.user.last_name) %>

<%=h item("Site:", @ticket.room.location.name) %>

<%=h item("Room:", @ticket.room.name) %>

<%= if @ticket.status == "Closed" then 
      item("Status:", @ticket.status + " (" + @ticket.closed_at.to_s + ")") 
    else
      item("Status:", @ticket.status)
    end
%>

<%=h item("Contact:", if @ticket.quick_contact_name then @ticket.quick_contact_name else "&nbsp" end) %>

<%=h item("Contact Number:", if @ticket.quick_contact_telephone then @ticket.quick_contact_name else "&nbsp" end) %>

<%=h item("Client ticket:", if @ticket.client_ticket_number then @ticket.client_ticket_number else "&nbsp" end) %>

<br />

<div class="span-16 last">
  <b>Subject:</b><br />
  <div class="span-16 smallbox white">
  <%= @ticket.subject %>
</div>
</div>

<div class="span-16 append-6 last">
  <b>Description:</b><br />
  <div class="span-16 smallbox white">
  <%= @ticket.description %>
</div>
</div>

<div class="span-4 last">
<b>Notes:</b><br />
</div>

   <div class="span-24 append-6 last">
<% 
  if @ticket.notes then
   @ticket.notes.each do |note| %>
    <div class="field <%= cycle("even", "odd") %> span-16 smallbox white">
    <%= note.text %>
    </div>
    <div class="span-3 smallbox last">
    <%= note.user.full_name %> 
    </div>

    <div class="span-4 smallbox last">
    <% if note.backdate then %>
    <%= note.backdate.to_s %> 
    <% else %>
    <%= note.created_at.to_s %>
    <% end %>
    </div>

 <% end %>
<%  end %>

</div>

<div id="notes_form" class="span-16 append-6 last">
</div>

<div class="span-4">
<%= link_to 'Add note', new_note_path(:ticket_id => @ticket.id) %> |
<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>
</div>